### ISSUE TITLE
TypeError: mix.js(...).postCss is not a function

### ISSUE THREAD

**Issue by aminraeisi** [michaeldyrynda/laravel-preset-tailwind#10]
I am getting the following error when running `npm run dev` : 

TypeError: mix.js(...).postCss is not a function
    at Object.<anonymous> (/home/amin/testTailwind/webpack.mix.js:17:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Mix.initialize (/home/amin/testTailwind/node_modules/laravel-mix/src/Mix.js:46:13)
    at Object.<anonymous> (/home/amin/testTailwind/node_modules/laravel-mix/setup/webpack.config.js:18:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amin/.npm/_logs/2017-12-01T18_05_52_174Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amin/.npm/_logs/2017-12-01T18_05_52_187Z-debug.log

**Comment by michaeldyrynda** [comment]
Are you able to provide more information about your environment? Specifically what version of Mix you're running in the first instance?

**Comment by aminraeisi** [comment]
"tailwindcss": "^0.2.2",
"laravel-mix": "^0.8.3"

and laravel 5.5

Update: forgot to mention that I have installed this on an existing test project so maybe that it the problem?

**Comment by michaeldyrynda** [comment]
I would be careful using the preset in an existing function, or at the very least having the project in version control because things will be changed/removed.

You'll need a newer version of Mix, though. `postCss` was added to the public API in 1.4.0.
